
ALTER TABLE recipeSearch
MODIFY COLUMN image VARCHAR(255) DEFAULT NULL,
MODIFY COLUMN label VARCHAR(255) DEFAULT NULL,
MODIFY COLUMN url VARCHAR(255) DEFAULT NULL,
MODIFY COLUMN cal DOUBLE DEFAULT NULL;

