ALTER TABLE recipeSearch
MODIFY COLUMN image VARCHAR(255) DEFAULT NULL;

ALTER TABLE recipeSearch
MODIFY COLUMN label VARCHAR(255) DEFAULT NULL;

ALTER TABLE recipeSearch
MODIFY COLUMN url VARCHAR(255) DEFAULT NULL;

ALTER TABLE recipeSearch
MODIFY COLUMN cal DOUBLE DEFAULT NULL;
