CREATE TABLE recipeSearch (
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    image VARCHAR(255)NOT NULL,
    label VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    cal DOUBLE NOT NULL
);


