ALTER TABLE recipeSearch
ADD COLUMN add_query VARCHAR(255) DEFAULT NULL,
ADD COLUMN diet_labels VARCHAR(255) DEFAULT NULL,
ADD COLUMN cuisine_type VARCHAR(255) DEFAULT NULL,
ADD COLUMN meal_type VARCHAR(255) DEFAULT NULL;
