CREATE TABLE posts (
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  post_title VARCHAR(255) NOT NULL,
  post_image VARCHAR(255)NOT NULL,
  post_body TEXT NOT NULL,
  published TINYINT(1) DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);